import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'


const Home: NextPage = () => {
  return (
    <div className='min-h-screen bg-[#060809]'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* <div className='bg-[#0c1012] p-12 border-2 border-[#1f2937] rounded-md text-white m-2'>
        hi
      </div> */}
      
    </div>
  )
}

export default Home
