export const objects: {value: string, label: string}[] = [
  {value: 'Animal 🐘', label: 'Animal 🐘'},
  {value: 'Cat 🐱', label: 'Cat 🐱'},
  {value: 'Dog 🐶', label: 'Dog 🐶'},
  {value: 'Person 🧍', label: 'Person 🧍'},
  {value: 'Couple 🧑🏻‍🤝‍🧑🏻', label: 'Couple 🧑🏻‍🤝‍🧑🏻'},
  {value: 'Group 👨‍👩‍👧‍👧', label: 'Group 👨‍👩‍👧‍👧'},
  {value: 'Toilet 🚽', label: 'Toilet 🚽'},
  {value: 'Hotel 🛏️', label: 'Hotel 🛏️'},
  {value: 'Girlfriend 👧', label: 'Girlfriend 👧'},
  {value: 'BoyFriend 👦', label: 'BoyFriend 👦'},
  {value: 'Company 🏢', label: 'Company 🏢'},
  {value: 'House 🏠', label: 'House 🏠'},
  {value: 'City🏙️', label: 'City🏙️'},
  {value: 'Country🗾', label: 'Country🗾'},
  {value: 'Continent🗺️', label: 'Continent🗺️'},
  {value: 'Planet🌍', label: 'Planet🌍'},
  {value: 'Car🚗', label: 'Car🚗'},
  {value: 'Train🚄', label: 'Train🚄'},
  {value: 'Airplane✈️', label: 'Airplane✈️'},
  {value: 'Rocket🚀', label: 'Rocket🚀'},
  {value: 'Boat⛵', label: 'Boat⛵'},

];